__tests__/fixtures/basic/pages/index.jsx
__tests__/index.js
hydrate.js

This change allows the standard makdown elements to be customized with the `components` object
Fixes #4

Allow the customization of standard markdown elements

---

README.md
__tests__/fixtures/basic/mdx/test.mdx
__tests__/fixtures/basic/pages/index.jsx
babel-plugin-mdx-browser.js
hydrate.js
package-lock.json
package.json
render-to-string.js

Hey! 👋 
This PR brings `next-mdx-remote` more in line with how the mdx-runtime works.
see: https://github.com/mdx-js/mdx/blob/master/packages/runtime/src/index.js
Great work over here by the way, I like what you're doing

add scoped variables

---

hydrate.js
idle-callback-polyfill.js

Previously there was a bug where, if the `source` was updated without a full page reload, the content would not update. This resolves that bug and cleans up the code a little as well 😀
Closes #6

Fix hydration not happening on client-side page transition

---

README.md
__tests__/fixtures/basic/pages/index.jsx
__tests__/index.js
hydrate.js
render-to-string.js

As this library has developed, we have reached the point where there are too many direct arguments being passed to the function, meaning there are a few valid use cases where passing options like `renderToString(x, y null, z)` are quite normal. This is the point at which, for me, the function signature needs to be re-examined. Additionally, it was not entirely clear what arguments were required vs optional. This PR introduces a new function signature that I feel is better in every way and allows for future features to be added without pain, but it is a massively breaking change so will have to go out as a major version I think.

Improve function signatures

---

package-lock.json
package.json

They are required as peer deps for nextjs already - this will prevent any potential misalignment of react versions and/or hooks errors.

move react and react-dom to peer deps

---

README.md

gray-matter is not recognizing front matter because of a new line character at the end. Hence, removed the new line character in README.

Fix README for frontmatter

---

.npmignore
README.md
__tests__/index.ts
babel.config.js
hydrate.d.ts
index.d.ts
package-lock.json
package.json
render-to-string.d.ts
render-to-string.js
tsconfig.json
types.d.ts

There has been a long standing PR to convert this entire library to typescript that has been plagued with a variety of issues stemming from its lack of default exports and two separate exports. In the meantime, perhaps we can bridge the gap by just providing typings. I pulled this out of one I wrote in a consuming typescript library, but I am not great at typescript so any thoughts here appreciated. If this works out, will write one for renderToString and ship it as major, call it a day for now!

Typescript Type Definitions

---

hydrate.d.ts

According to the hydrate function, the seconds parameter `options` is not required nor the property `components` inside of the `options` object.
This PR goal is to adjust the Typescript definition to represent correctly the hydrate function.
https://github.com/hashicorp/next-mdx-remote/blob/5958c0583595176ab2b44dab227270e685d77925/hydrate.js#L7-L11

fix: Typescript definition of the hydrate function

---

package.json

Having upgraded react to 17.0.1 on my next js blog seems to be working with next-mdx-remote.
It is for example used on this blog.
https://nextjs.marcofranssen.nl/blog/building-a-elasticsearch-cluster-using-docker-compose-and-traefik 
This PR includes react 17.0.1 as a peer dependency to remove the npm warning.

Fix peer dependencies to include react 17.0.1

---

hydrate.d.ts
index.d.ts
render-to-string.d.ts
tsconfig.json

I noticed that the return types weren't showing up as expected when consuming the types, and I believe it is because of the non-relative imports being used here. They worked in the source because of our `baseUrl: "."` setting, but not during consumption.

fix: relative type imports so they work when consumed

---

README.md

MDXProvider not only let you inject custom components but also customize the rendering of the main components, like titles and stuff.
This is needed if you want to use material UI for instance.
This means during hydratation, you need to inject your components.
~~Something I don't get: why do you need to add `components` twice, during render to string and during hydratation , for custom MDX components like `<Test />`? This is not the case for HTML tags like "h1".~~
Yeah actually you need it during string render as well for SSR, makes sense.
One small difference also, the key `"th/td"` gave a syntax error, while it is normally valid: "SyntaxError: Arg string terminates parameters early"

Add example of replacing HTML tags as well

---

__tests__/index.tsx
src/index.tsx

closes #127 
v3 accidentally broke usage of fragments, as React is no longer in scope. This adds a test case and once again passes React into `scope` when the compiled MDX source is rendered.

fix: usage of fragments in MDX

---

src/serialize.ts

Rely on node's native `require.resolve` method to determine where its binary lives.
fixes #134

fix(serialize): make esbuild resolution more reliable

---

README.md

The readme had some minor inaccuracies in how the `scope` argument could be used, and was also missing an important caveat -- that keys to `scope` must be valid as javascript variable names. This should make that more clear!

Clarify scope argument in readme

---

README.md

This deletes the table of contents at the top of the readme.
- Github recently built a TOC into their UI
- ![image](https://user-images.githubusercontent.com/26389321/124186520-6c2a8500-da8a-11eb-8b10-277950833dbb.png)
- This is one less _thing_ that needs to be maintained
This adds a section + link to the V3 breaking chanes
- This took me a while to discover, and I also discovered by chance when I wanted to upgrade from V2 to V3.

Delete TOC; add link to Migration notes

---

__tests__/index.tsx
src/serialize.ts

If you create a single options object and pass that to multiple invocations of `serialize`, you'll notice that the `remarkPlugins` array will grow by 1 during each invocation. This is because we're modifying shared data.
We're making a copy of `remarkPlugins`, but we're dealing with a reference to the same `mdxOptions` object
eg:
```
const options = { mdxOptions: remarkPlugins: [] };
await serialize(foo, options);
// options.mdxOptions.remarkPlugins.length === 1
await serialize(foo, options);
// options.mdxOptions.remarkPlugins.length === 2
```
Impact:
`serialize()` slows down after each subsequent invocation if being passed the same options object (which is perfectly reasonable to do)

Don't modify the options passed in

---

README.md

SSIA
When using MDXProvider in _app.jsx, individual page components do not require MDXProvider. 👍

docs: remove unnecessary MDXProvider in README

---

package.json

Ref https://github.com/hashicorp/next-mdx-remote/issues/218

Add "main" field to avoid node ESM deprecation warning

---

README.md

getStaticProps would error out with: Property 'compiledSource' is missing in type '{ mdxSource: MDXRemoteSerializeResult<Record<string, unknown>>; componentNames: (string | null)[]; }' but required in type 'MDXRemoteSerializeResult<Record<string, unknown>>'.

Fixed Type Error in Typescript Section

---

src/types.ts

Changed the type of the `frontmatter` prop to better reflect which values it can potentially take on: `null`, `boolean`, `number`, `string`, `Array`, or `Object` (where the latter two recursively allow any of those types). 
Closes #249

Improved typing of the `frontmatter` prop.

---

__tests__/integration.test.tsx
package-lock.json
package.json
rollup.config.js
src/index.tsx
src/jsx-runtime.cjs
src/jsx-runtime.cjs.d.ts

Ensure that we can support both react 17 and react 18, considering the changes that were made to the `react/jsx-runtime` export in React 18. Validated by using `create-next-app -e with-mdx-remote` and testing the changes against both react 17 and react 18.
Related to #255, #261
closes #260, closes #266, closes #254, closes #258

fix: support both react 17 and react 18 jsx-runtime imports

---

README.md

chore: update reference to MDX options

---

src/types.ts

Fix https://github.com/hashicorp/next-mdx-remote/issues/269 by reverting https://github.com/hashicorp/next-mdx-remote/pull/252 and making `frontmatter`'s type overrideable through a generic param. 
cc @BRKalow

fix: loosen `frontmatter` type and make it configurable

---

.jest/utils.tsx
__tests__/serialize.test.tsx
src/serialize.ts

This PR adds support for serializing arbitrary VFile-compatible values, not just strings. This takes advantage of the fact that the `VFile` constructor supports a string, Buffer, or an existing `VFile` object ([source](https://github.com/vfile/vfile/blob/5181b5d0be113a6cb698be123d1226aadcac720c/lib/index.js#L61-L77)).
Closes #309.

Support serializing all VFile-compatible values

---

package-lock.json
package.json
src/jsx-runtime.cjs

From `@mdx-js/mdx` version 2.2.0 onwards, the compiled source uses `jdxDEV` from `react/jsx-dev-runtime` in development mode rather than `jdx-runtime`. This patch determines whether we should export `jsx-dev-runtime` by checking `process.env.NODE_ENV`. This environment variable should be always present in Next.js in both browser and server environment. `@mdx-js/*` are bumped to `^2.2.1` because this change is incompatible with version 2.1.5 or older.
Fixes `TypeError: _jsxDEV is not a function` error https://github.com/hashicorp/next-mdx-remote/issues/307#issuecomment-1352299456

Fix: export `jsx-dev-runtime` in development mode

---

src/index.tsx

This will make it easier to add support for React Server Components in a follow-up PR.
MDX already takes a `components` prop so the additional context provider is not needed.

Pass components directly to compiled MDX function

---

README.md
src/index.tsx
src/rsc.tsx

- Adds documentation for the new `next-mdx-remote/rsc` API
- Adds back usage of `MDXProvider` in the stable API to avoid any brekage
- Refine types for the RSC `MDXRemote` export
👉 [Rendered docs](https://github.com/hashicorp/next-mdx-remote/tree/brk.docs/rsc#react-server-components-rsc--nextjs-app-directory-support) 👈

chore: document new RSC API

---

__tests__/integration.test.tsx
src/rsc.tsx

Update types in our RSC APIs to not required `compiledSource`, as everything is handled internally.
fixes #336

fix(rsc): do not require compiledSource in types

---

README.md
__tests__/rsc.test.tsx
src/rsc.tsx
src/serialize.ts
src/types.ts

Update `serialize()` and `compileMDX()` to accept generics for `scope` and `frontmatter`. Pass through the generic to ensure that the return types reflect the provided frontmatter types.
`serialize`:
```ts
import { serialize } from 'next-mdx-remote/serialize'
interface Frontmatter {
title: string
published: string
description?: string
}
//     👇 should have type Frontmatter
const { frontmatter } = serialize<Record<string, unknown>, Frontmatter>(source)
```
`compileMDX`:
```tsx
import { compileMDX } from 'next-mdx-remote/rsc'
interface Frontmatter {
title: string
published: string
description?: string
}
export default async function Page({ source }) {
//              👇 should have type Frontmatter
const { content, frontmatter } = await compileMDX<Frontmatter>(source)
return (
<> …
```

feat: Improve frontmatter types, pass generic TFrontmatter type through

---

README.md

This PR updates the README to reflect that the Next.js App Router is now stable! :tada: (Note: Our own API isn't yet though! 😅)

docs: reflect that app router is stable

---

.jest/utils.tsx

This PR updates the expected "ready" message in `startDevServer` to reflect the new output used by Next.js v13.5.6, which gets CI green again.

fix: watch for the correct log message

---

index.d.ts
rsc.d.ts
serialize.d.ts

This PR adds explicit file extensions to the type imports for the root-level files.
Fixes #329

fix: add extension to type imports

---

__tests__/rsc.test.tsx
__tests__/serialize.test.tsx
package-lock.json
src/serialize.ts
src/types.ts

This PR restores the option `useDynamicImport`, which allows users to opt-in to having `import`/`export` statements retained in the emitted MDX.
> [!CAUTION]
> This feature likely doesn't work as intended, and is being added to `v5` solely to retain API compatibility with `v4`. If your code relies on using `useDynamicImport` please leave a comment so we can better understand your use case.

feat: restore useDynamicImport
